name: 'post-pr-comment'
on:
  workflow_run:
    workflows: ["pr-approved"]
    types:
      - completed

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - name: 'Comment PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for the review (to deploy soon)!'
            })