name: pr-approved

on:
  pull_request_review:
    types: [submitted]
    branches: ['master']

jobs:
  set-state:
    runs-on: ubuntu-latest
    outputs:
      pr_approved: ${{ github.event.review.state == 'approved' }}
      deploy_prod: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
      deploy_dev: ${{ contains(github.event.pull_request.labels.*.name, 'deploy:dev')}}
    steps:
      - name: check fork
        # The GH token used when a PR is a fork is read-only, for security reasons
        # (so the forked PR can't steal secrets, for example)
        # This prevents us from adding comments, etc. So the requirements are:
        #     1. the PR must be from a branch in the same repo
        #     2. consequently, the PR creator must be a Contributor to the repo
        # This ensures trust, and the GH token will thus be read-write.
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "::error::PRs from forks are not supported (Github security issue).%0APRs should be from a branch in the same repo, created by a Contributor."
          exit 1

  echo-state:
    needs: [set-state]
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR Review State - ${{ github.event.review.state }}"
      - run: echo "PR Labels - ${{ join(github.event.pull_request.labels.*.name, ',') }}"
      - run: echo "PR Approved - ${{ needs.set-state.outputs.pr_approved }}"
      - run: echo "Deploy - ${{ needs.set-state.outputs.deploy_prod }}"
      - run: echo "Deploy Dev - ${{ needs.set-state.outputs.deploy_dev }}"

  pre-build-dev:
    needs: [set-state]
    runs-on: ubuntu-latest
    if: needs.set-state.outputs.pr_approved == 'true' && needs.set-state.outputs.deploy_dev == 'true'
    steps:
      - name: 'Comment PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⏳ Start deploy to dev'
            })

  pre-build-production:
    needs: [set-state]
    runs-on: ubuntu-latest
    if: needs.set-state.outputs.pr_approved == 'true' && needs.set-state.outputs.deploy_prod == 'true'
    steps:
      - name: 'Comment PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⏳ Start deploy to production'
            })

  build-dev:
    needs: [pre-build-dev]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "approved (dev)"

  build-production:
    needs: [pre-build-production]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "approved (prod)"

  post-build-dev:
    needs: [build-dev]
    runs-on: ubuntu-latest
    steps:
      - name: 'Comment PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🏄🏽‍♂️ Deployed to dev'
            })

  post-build-production:
    needs: [build-production]
    runs-on: ubuntu-latest
    steps:
      - name: 'Comment PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🏄🏽‍♂️ Deployed to production'
            })            