name: pr-approved

on:
  pull_request_review:
    types: [submitted]
    branches: ['master']

jobs:
  set-state:
    runs-on: ubuntu-latest
    outputs:
      pr_approved: ${{ github.event.review.state == 'approved' }}
      deploy_prod: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
      deploy_dev: ${{ contains(github.event.pull_request.labels.*.name, 'deploy:dev')}}
    steps:
      - run: echo 'Set state'

  echo-state:
    needs: [set-state]
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR Review State - ${{ github.event.review.state }}"
      - run: echo "PR Labels - ${{ join(github.event.pull_request.labels.*.name, ',') }}"
      - run: echo "PR Approved - ${{ needs.set-state.outputs.pr_approved }}"
      - run: echo "Deploy - ${{ needs.set-state.outputs.deploy_prod }}"
      - run: echo "Deploy Dev - ${{ needs.set-state.outputs.deploy_dev }}"

  build-dev:
    needs: [set-state]
    runs-on: ubuntu-latest
    if: needs.set-state.outputs.pr_approved == 'true' && needs.set-state.outputs.deploy_dev == 'true'
    steps:
      - uses: actions/checkout@v2
      - run: echo "approved (dev)"

  build-production:
    needs: [set-state]
    runs-on: ubuntu-latest
    if: needs.set-state.outputs.pr_approved == 'true' && needs.set-state.outputs.deploy_prod == 'true'
    steps:
      - uses: actions/checkout@v2
      - run: echo "approved (prod)"
      - name: 'Comment PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for the review (to deploy soon)!'
            })