name: Respond to Pull Request

on:
  pull_request_review:
    types: [submitted]
    branches: ['master']

jobs:
  echo:
      runs-on: ubuntu-latest
      steps:
        - name: State Check
          run: |
            echo ${{ 'PR Review State: ' + github.event.review.state }}
            echo ${{ 'PR Labels: ' + join(github.event.pull_request.labels.*.name, ',') }}
  build-production:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved' && contains(github.event.pull_request.labels.*.name, 'deploy')
    steps:
      - uses: actions/checkout@v2
      - name: job name
        run: |
          echo "approved (prod)"
  build-dev:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved' && contains(github.event.pull_request.labels.*.name, 'deploy:dev')
    steps:
      - uses: actions/checkout@v2
      - name: job name
        run: |
          echo "approved (dev)"
