name: Respond to Pull Request

on:
  pull_request_review:
    types: [submitted]
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved' && contains(github.event.pull_request.labels, 'deploy')
    steps:
      - uses: actions/checkout@v2
      - name: job name
        run: |
          echo "approved"
  echo:
      runs-on: ubuntu-latest
      steps:
        - name: State Check
          run: |
            echo ${{ github.event.review.state }}
            echo ${{ join(github.event.pull_request.labels.*.name, ',') }}
