name: Respond to Pull Request

on:
  pull_request_review:
    types: [submitted]
    branches: ['master']

jobs:
  build:
    if: github.event.review.state == 'approved' && github.event.pull_request.labels.includes('deploy')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: job name
        run: |
          echo "approved"