name: Pull Request (approved, label as 'deploy' or 'deploy:dev')

on:
  pull_request_review:
    types: [submitted]
    branches: ['master']

jobs:
  set-state:
      runs-on: ubuntu-latest
      outputs:
        pr_approved: ${{ github.event.review.state == 'approved' }}
        deploy_prod: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
        deploy_dev: ${{ contains(github.event.pull_request.labels.*.name, 'deploy:dev')}}
      steps:
        - name: echo state
          run: |
            echo "PR Review State: " ${{ github.event.review.state }}
            echo "PR Labels: " ${{ join(github.event.pull_request.labels.*.name, ',') }}
  build-production:
    needs: [set-state]
    runs-on: ubuntu-latest
    if: needs.set-state.outputs.pr_approved == 'true' && needs.set-state.outputs.deploy_prod == 'true'
    steps:
      - uses: actions/checkout@v2
      - run: echo "PR Approved " ${{ needs.set-state.outputs.pr_approved }}
      - run: echo "Deploy " ${{ needs.set-state.outputs.deploy_prod }}

  build-dev:
    needs: [set-state]
    runs-on: ubuntu-latest
    if: needs.set-state.outputs.pr_approved == 'true' && needs.set-state.outputs.deploy_dev == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: build (dev)
        run: echo "approved (dev)"
